export * from './load-shark-detail-controller'
export * from '@main/factories/shark/load-shark-detail-factory'
export * from './load-shark-detail-model'
export * from './load-shark-detail-service'
export * from './protocols'
